install proxmark custom package on laptop

diff --git a/host/node5/backup b/host/node5/backup
--- a/host/node5/backup
+++ b/host/node5/backup
@@ -1,11 +1,19 @@
-#!/run/current-system/sw/bin/bash
-
 net=$(ip a | grep "192\.168\.178")
 if [ $? -ne 0 ]; then
 	exit 1
 fi
 
-remote=$(ssh pvehome "zfs list -t snap -r rpool/backup/node5 | tail -n 1 | awk '{print \$1}' | awk -F'@' '{print \$2}'")
-local=$(zfs list -t snap -r rpool/nixos/home | tail -n 1 | awk '{print $1}')
+sshcommand="ssh -i /root/.ssh/backup root@192.168.178.123"
 
-zfs send --raw -i rpool/nixos/home@$remote $local | ssh pvehome "zfs recv rpool/backup/node5"
+remote=$($sshcommand "zfs list -t snap -r rpool/backup/node5 | tail -n 1 | awk '{print \$1}' | awk -F'@' '{print \$2}'")
+local=$(zfs list -t snap -r rpool/nixos/home | tail -n 1 | awk '{print $1}')
+remote="rpool/nixos/home@$remote"
+if [ "$local" != "$remote" ]; then
+	zfs send --raw -i $remote $local | $sshcommand "zfs recv rpool/backup/node5"
+	if [ $? -ne 0 ]; then
+		echo "an error occured"
+	fi
+else
+	echo "nothing to copy"
+fi
+
